language: node_js
dist: trusty
node_js:
- node
deploy:
  provider: npm
  email: michael.emmi@gmail.com
  on:
    tags: true
env:
  global:
    secure: Q6oyVn87Z1BXZQmERDMoLQx6wCbcGMMsHiDePhZiPVCcoq1/3EtZb5ebIhpMlKcpqQJ1735UqdHIWnk2oNTwjwMlEVTBxrEUG2ee3bmVhPE2L4XzP1UzLh199ddnTE5ARL4PKAlqYDZeexGBFrF1PgIPSDCjwiPEwSlRSvul8ukc2LIhxhTb9yEBNrT044W9OBssWYPD3zFjdc7YAKbJCvXLrBcLlJonKb4n5IVUwCEJgcYb09BXdzYQEQSpqRx5pJFeY9fVLKXzpkyajN4xN60RZhlu6m9wKvugBDbud+a37uG/BduKMeWHXfn8T2V25Ru6LjseXVPCjvaJ7ROwkMG8hrxpFJPHzw6kSGkfK1txohl99EZmgWRHGk9fh0kML9mwA4rQhj/TJ4cVQPHUoly6sNWuMtCzAIHlSXxE0i8yPIhIIsjt/fbEjtpnUeAtKZoXpHv+BHf139yQRrxl1OYJt49LAocVPPaxrdja5uiicUboYnlaaLi5d4ojP+H/nys+RMY7GmfC9q76JWIdu0kyWWQwKXkNdOZDBdXBc9DJNQFX49eDt+B9MeyKZ/R1GTsRGh/wZPqR2DCsO9wca+TTJFnKUrHYp6ZZ8w95xDMNqiLts7CyYtbsl4sTHKoHg6PP/cryfcDHHjhQiOsnXiofihvRrfXvrNAo9F74Wbc=
